name: Auto Deploy to Server

on:
    push:
        branches: main # Срабатывает при пуше в main ветку
    workflow_dispatch: # Позволяет запустить workflow вручную

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  port: ${{ secrets.SERVER_PORT || 22 }}
                  timeout: 60s
                  command_timeout: 10m
                  script: |
                      echo "Starting deployment..."
                      cd ${{ secrets.PROJECT_PATH }}
                      echo "Current directory: $(pwd)"
                      git fetch origin
                      git reset --hard origin/main
                      git pull origin main
                      echo "Deployment completed at $(date)"
